---
apiVersion: apps/v1
kind: {{ target.kind }}
metadata:
  name: {{ target.name }}
spec:
  template:
    metadata:
      labels:
      {% for egress in my.egresses() %}
        networking/egress-to-{{ egress.shortname }}: enabled
      {% endfor %}
